In [2]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [1]:
items = [
    ["bread","milk","butter","jam"],
    ["bread","butter","milk"],
    ["bread","juice","curd"],
    ["bread","milk","juice"],
    ["butter","milk","juice"]
]
items

[['bread', 'milk', 'butter', 'jam'],
 ['bread', 'butter', 'milk'],
 ['bread', 'juice', 'curd'],
 ['bread', 'milk', 'juice'],
 ['butter', 'milk', 'juice']]

In [4]:
t_encoder = TransactionEncoder()
ecoded_items = t_encoder.fit_transform(items)

feature_names = t_encoder.get_feature_names_out()
feature_names

array(['bread', 'butter', 'curd', 'jam', 'juice', 'milk'], dtype=object)

In [6]:
df = pd.DataFrame(ecoded_items,columns=feature_names)
df

   bread  butter   curd    jam  juice   milk
0   True    True  False   True  False   True
1   True    True  False  False  False   True
2   True   False   True  False   True  False
3   True   False  False  False   True   True
4  False    True  False  False   True   True

In [8]:
frequent_pattern = apriori(df,min_support=0.5,use_colnames=True)
frequent_pattern

   support        itemsets
0      0.8         (bread)
1      0.6        (butter)
2      0.6         (juice)
3      0.8          (milk)
4      0.6   (bread, milk)
5      0.6  (butter, milk)

In [9]:
x = association_rules(frequent_pattern,metric='confidence',min_threshold=0.7)
x

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(bread),(milk),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
1,(milk),(bread),0.8,0.8,0.6,0.75,0.9375,1.0,-0.04,0.8,-0.25,0.60,-0.250,0.750
2,(butter),(milk),0.6,0.8,0.6,1.00,1.2500,1.0,0.12,inf,0.50,0.75,1.000,0.875
3,(milk),(butter),0.8,0.6,0.6,0.75,1.2500,1.0,0.12,1.6,1.00,0.75,0.375,0.875

In [11]:
a = x.iloc[:,[0,1,4,5]]
a

  antecedents consequents  support  confidence
0     (bread)      (milk)      0.6        0.75
1      (milk)     (bread)      0.6        0.75
2    (butter)      (milk)      0.6        1.00
3      (milk)    (butter)      0.6        0.75