In [26]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

In [27]:
items= [
    ['Laptop', 'Mouse'],
    ['Keyboard', 'Mouse', 'Headphones'],
    ['Laptop', 'Keyboard'],
    ['Laptop', 'Mouse', 'Keyboard'],
    ['Monitor', 'Keyboard'],
    ['Laptop', 'Monitor', 'Mouse'],
    ['Mouse', 'USB Drive'],
    ['Laptop', 'Headphones'],
    ['Keyboard', 'Mouse', 'USB Drive'],
    ['Laptop', 'Mouse', 'Monitor']
]
items

[['Laptop', 'Mouse'],
 ['Keyboard', 'Mouse', 'Headphones'],
 ['Laptop', 'Keyboard'],
 ['Laptop', 'Mouse', 'Keyboard'],
 ['Monitor', 'Keyboard'],
 ['Laptop', 'Monitor', 'Mouse'],
 ['Mouse', 'USB Drive'],
 ['Laptop', 'Headphones'],
 ['Keyboard', 'Mouse', 'USB Drive'],
 ['Laptop', 'Mouse', 'Monitor']]

In [28]:
t_encoder = TransactionEncoder()
ecoded_items = t_encoder.fit_transform(items)

feature_names = t_encoder.get_feature_names_out()
feature_names

array(['Headphones', 'Keyboard', 'Laptop', 'Monitor', 'Mouse',
       'USB Drive'], dtype=object)

In [29]:
df = pd.DataFrame(ecoded_items,columns=feature_names)
df

   Headphones  Keyboard  Laptop  Monitor  Mouse  USB Drive
0       False     False    True    False   True      False
1        True      True   False    False   True      False
2       False      True    True    False  False      False
3       False      True    True    False   True      False
4       False      True   False     True  False      False
5       False     False    True     True   True      False
6       False     False   False    False   True       True
7        True     False    True    False  False      False
8       False      True   False    False   True       True
9       False     False    True     True   True      False

In [39]:
frequent_pattern = fpgrowth(df,min_support=0.4,use_colnames=True)
frequent_pattern

   support         itemsets
0      0.7          (Mouse)
1      0.6         (Laptop)
2      0.5       (Keyboard)
3      0.4  (Laptop, Mouse)

In [40]:
rules = association_rules(
    frequent_pattern,
    metric='confidence',
    min_threshold=0.5
)

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Laptop),(Mouse),0.6,0.7,0.4,0.666667,0.952381,1.0,-0.02,0.900000,-0.111111,0.444444,-0.111111,0.619048
1,(Mouse),(Laptop),0.7,0.6,0.4,0.571429,0.952381,1.0,-0.02,0.933333,-0.142857,0.444444,-0.071429,0.619048

In [41]:
a = rules.iloc[:,[0,1,4,5]]
a

  antecedents consequents  support  confidence
0    (Laptop)     (Mouse)      0.4    0.666667
1     (Mouse)    (Laptop)      0.4    0.571429