In [12]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.read_csv('svm/taxi_trip_pricing.csv')
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       950 non-null    float64
 1   Time_of_Day            950 non-null    object
 2   Day_of_Week            950 non-null    object
 3   Passenger_Count        950 non-null    float64
 4   Traffic_Conditions     950 non-null    object
 5   Weather                950 non-null    object
 6   Base_Fare              950 non-null    float64
 7   Per_Km_Rate            950 non-null    float64
 8   Per_Minute_Rate        950 non-null    float64
 9   Trip_Duration_Minutes  950 non-null    float64
 10  Trip_Price             951 non-null    float64
dtypes: float64(7), object(4)
memory usage: 86.1+ KB

In [5]:
x = df.drop('Trip_Price',axis=1)
y = df['Trip_Price']

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
x_test

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes
521,19.66,Night,Weekday,2.0,Low,Clear,4.56,1.73,0.44,105.23
737,41.01,Morning,NaN,1.0,Medium,Clear,3.95,1.80,0.42,16.56
740,23.67,Evening,Weekday,1.0,Medium,Snow,4.76,1.73,0.38,43.49
660,18.45,Afternoon,Weekday,4.0,Medium,Clear,2.46,1.59,0.49,109.53
411,47.55,Morning,Weekday,4.0,Low,Clear,4.78,1.97,0.27,94.35
...,...,...,...,...,...,...,...,...,...,...
408,45.36,Afternoon,Weekend,NaN,Medium,Rain,2.66,1.78,0.26,68.68
332,1.71,Morning,Weekday,4.0,High,Clear,4.45,1.27,0.18,87.85
208,1.25,NaN,Weekday,3.0,Low,Rain,3.97,1.49,0.31,12.80
613,5.01,Afternoon,Weekend,4.0,Low,Rain,3.63,0.79,0.37,58.02
78,18.56,Morning,Weekend,1.0,Medium,Snow,4.74,NaN,0.47,44.62

In [11]:
cat = ['Time_of_Day','Day_of_Week','Traffic_Conditions','Weather']

In [13]:
cat_pipeline = Pipeline([
    ('one_hot', OneHotEncoder())
])

In [16]:
cat_pipeline

Pipeline(steps=[('one_hot', OneHotEncoder())])

In [14]:
preprocessor = ColumnTransformer(
    transformers=[
        (cat_pipeline,cat)
    ]
)

In [22]:
preprocessor

ColumnTransformer(transformers=[(Pipeline(steps=[('one_hot', OneHotEncoder())]),
                                 ['Time_of_Day', 'Day_of_Week',
                                  'Traffic_Conditions', 'Weather'])])

OneHotEncoder()